version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prueba_go_prod
    ports:
      - 4010:4000
    # depends_on:
    #   - mysql
    # volumes:
    #   - ./:/app
#   mysql:
#     image: mysql:5.7 
#     container_name: menekel_mysql
#     command: mysqld --user=root
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_DATABASE=article
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_ROOT_PASSWORD=root
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 5s
#       retries: 10