version: "3.3"
services:

  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: main_dev
    ports:
      - 4000:4000
      - 4010:4010
    # depends_on:
    #   - mysql
    volumes:
      - ./:/app
    restart: always

#   mysql:
#     image: mysql:5.7 
#     container_name: menekel_mysql
#     command: mysqld --user=root
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_DATABASE=article
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_ROOT_PASSWORD=root
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 5s
#       retries: 10

  redis:
    image: "redis:alpine"
    command: redis-server
    container_name: redis
    #command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
    - "6379:6379"
    restart: always

    # volumes:
    # - $PWD/redis-data:/var/lib/redis
    #   - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    # environment:
    # - REDIS_REPLICATION_MODE=master

    # networks:
    #   node_net:
    #     ipv4_address: 172.28.1.4

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    #image: powerbim/powerbim_nginx:latest
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    #environment:      
    #   - VIRTUAL_PROTO=https
    #   - VIRTUAL_PORT=443
    #  - CERT_NAME=powerbim
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - /home/powerbim/certs:/etc/nginx/certs
      # - /home/powerbim/nginx/conf.d:/etc/nginx/conf.d
    restart: always

networks:
  default:
    external:
      name: nginx-proxy