version: "3.3"
services:
  # main_auth:
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   container_name: auth_dev
  #   ports:
  #     - 4010:4010
  #   # depends_on:
  #   #   - mysql
  #   volumes:
  #     - ./:/app
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: main_dev
    ports:
      - 4000:4000
      - 4010:4010
    # depends_on:
    #   - mysql
    volumes:
      - ./:/app
#   mysql:
#     image: mysql:5.7 
#     container_name: menekel_mysql
#     command: mysqld --user=root
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_DATABASE=article
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_ROOT_PASSWORD=root
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 5s
#       retries: 10