package cmd

import (
	"fmt"
	"goprueba/Services/auth/controller"
	"goprueba/Services/auth/service"
	_ "goprueba/docs" // docs is generated by Swag CLI, you have to import it.

	"net/http"
	"os"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

//http -v --json POST localhost:8000/login username=admin password=admin

func Mauth() {

	port := os.Getenv("AUTH_PORT")

	fmt.Printf("port auth: %v\n", port)
	r := gin.Default()

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong auth",
		})
	})

	var loginService service.LoginService = service.StaticLoginService()
	var jwtService service.JWTService = service.JWTAuthService()
	var loginController controller.LoginController = controller.LoginHandler(loginService, jwtService)

	server := gin.New()

	server.POST("/login", func(ctx *gin.Context) {
		token := loginController.Login(ctx)
		if token != "" {
			ctx.JSON(http.StatusOK, gin.H{
				"token": token,
			})
		} else {
			ctx.JSON(http.StatusUnauthorized, nil)
		}
	})

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	go r.Run(":" + port)

}
